
    create table categories (
        id bigint generated by default as identity,
        name varchar(100) not null,
        description TEXT not null,
        primary key (id)
    );

    create table payments (
        amount float(53) not null,
        balance float(53) not null,
        change float(53) not null,
        payment_date date not null,
        id bigint generated by default as identity,
        sale_id bigint not null,
        note varchar(255) not null,
        reference varchar(255) not null,
        primary key (id)
    );

    create table products (
        created_at date not null,
        expiry_date date not null,
        price float(53) not null,
        purchase_price float(53) not null,
        quantity integer not null,
        selling_price float(53) not null,
        updated_at date not null,
        category_id bigint not null,
        id bigint generated by default as identity,
        supplier_id bigint not null,
        barcode varchar(100) not null,
        name varchar(100) not null,
        description TEXT not null,
        primary key (id)
    );

    create table sale_items (
        quantity integer not null,
        total_amount float(53) not null,
        unit_price float(53) not null,
        id bigint generated by default as identity,
        sale_id bigint not null,
        primary key (id)
    );

    create table sales (
        discount float(53) not null,
        final_amount float(53) not null,
        sale_date date not null,
        total_amount float(53) not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        payment_method varchar(100) not null check ((payment_method in ('CASH','CREDIT_CARD','DEBIT_CARD','TRANSFER'))),
        status varchar(100) not null check ((status in ('PENDING','COMPLETED','CANCELLED'))),
        primary key (id)
    );

    create table stocks (
        created_at date not null,
        last_updated date,
        min_quantity integer not null,
        quantity float(53) not null,
        updated_at date not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        primary key (id)
    );

    create table suppliers (
        id bigint generated by default as identity,
        address varchar(100) not null,
        email varchar(100) not null,
        name varchar(100) not null,
        phone varchar(100) not null,
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        password varchar(100) not null,
        role varchar(100) not null check ((role in ('ADMIN','CUSTOMER','MANAGER','CASHIER'))),
        username varchar(100) not null,
        primary key (id)
    );

    alter table if exists payments 
       add constraint fk_payment_sale 
       foreign key (sale_id) 
       references sales;

    alter table if exists products 
       add constraint fk_product_category 
       foreign key (category_id) 
       references categories;

    alter table if exists products 
       add constraint fk_product_supplier 
       foreign key (supplier_id) 
       references suppliers;

    alter table if exists sale_items 
       add constraint fk_sale_item_sale 
       foreign key (sale_id) 
       references sales;

    alter table if exists sales 
       add constraint fk_sale_user 
       foreign key (user_id) 
       references users;

    alter table if exists stocks 
       add constraint fk_stock_product 
       foreign key (product_id) 
       references products;